### ISSUE TITLE
Security Vulnerability in Java Edition

### ISSUE THREAD

**Issue by MrTheoW** [sVoxelDev/minecraft-server-template#5]
Hi there,

Don't know if you have already seen [this Minecraft Official Announcement](https://www.minecraft.net/nl-nl/article/important-message--security-vulnerability-java-edition) but it seems there need to be an little change to the way the server is started.
Is this something we can do within the yml files?

Side note: Great job on this template! 👍

**Comment by Silthus** [comment]
Hi @MrTheoW 
thank you for the hint. As the template only uses the official itzg/minecraft-server images, this should already be mitigated by this issue: https://github.com/itzg/docker-minecraft-server/issues/1177

If running a production server you must make sure to update your docker images to the latest version by running:

```bash
./dc.sh pull
```
