### ISSUE TITLE
unexpected character first setup

### ISSUE THREAD

**Issue by gustaavik** [sVoxelDev/minecraft-server-template#6]
I just cloned the repository and finished the initial setup.
`$ ./dc.sh up -d
unexpected character "-" in variable name near "network-compression-threshold=256\r\nMAX_TICK_TIME=60000\r\nMAX_PLAYERS=100\r\nONLINE_MODE=false\r\nALLOW_FLIGHT=false\r\nBROADCAST_RCON_TO_OPS=true\r\nBROADCAST_CONSOLE_TO_OPS=true\r\nVIEW_DISTANCE=10\r\nMAX_BUILD_HEIGHT=256\r\nALLOW_NETHER=false\r\nENABLE_RCON=true\r\nSYNC_CHUNK_WRITES=true\r\nOP_PERMISSION_LEVEL=4\r\nPREVENT_PROXY_CONNECTIONS=false\r\nENTITY_BROADCAST_RANGE_PERCENTAGE=100\r\nPLAYER_IDLE_TIMEOUT=0\r\nDEBUG=false\r\nHARDCORE=false\r\nSPAWN_NPCS=false\r\nSPAWN_ANIMALS=false\r\nSNOOPER_ENABLED=false\r\nFUNCTION_PERMISSION_LEVEL=2\r\nLEVEL_TYPE=default\r\nSPAWN_MONSTERS=false\r\nENFORCE_WHITELIST=false\r\nSPAWN_PROTECTION=0\r\n"`

**Comment by MrTheoW** [comment]
I suggest trying it again from scratch... I had no problems at all with this template and I installed it about 2 months ago. Last edit on this repo was about 4 months ago.

**Comment by Silthus** [comment]
You could check your environment variables and see if there is anything funky going on there.
Take a look in the .env, globals, etc. and see if you have a `network-compression-threshhold` variable. It should be `NETWORK_COMPRESSION_THRESHHOLD`.

**Comment by gustaavik** [comment]
After I fix that, and try to run it I get this error:
https://pastebin.com/t8DrS5Xa

**Comment by gustaavik** [comment]
Oh wait it was because I didn't have docker running

**Comment by Silthus** [comment]
> Oh wait it was because I didn't have docker running

I assume it is working then and I will close the issue.
You can also drop by on Discord if your have any further questions or need support: https://discord.gg/KhpeW5TeMy
